<script setup>
import { computed, ref } from "vue"; import { onShow } from "@dcloudio/uni-app"; import { api,showError } from "../../services/api"; import { requireLogin } from "../../services/session";
function iso(d=new Date()){return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10)} const now=new Date(),start=new Date(now.getFullYear(),now.getMonth(),1);
const startDate=ref(iso(start)),endDate=ref(iso()),analysis=ref(null),budgets=ref([]),amount=ref(""),loading=ref(false); const month=computed(()=>startDate.value.slice(0,7)); const money=v=>Number(v||0).toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2});
async function load(ai=false){if(!requireLogin())return;loading.value=true;try{analysis.value=await api.analyze(startDate.value,endDate.value,ai);budgets.value=(await api.budgets()).filter(x=>x.month.startsWith(month.value))}catch(e){showError(e)}finally{loading.value=false}}
function preset(days){const d=new Date();d.setDate(d.getDate()-days+1);startDate.value=iso(d);endDate.value=iso();load()}
async function add(){if(!Number(amount.value))return;try{await api.createBudget(month.value,String(amount.value));amount.value="";await load()}catch(e){showError(e)}}
async function remove(id){await api.deleteBudget(id);await load()} onShow(()=>load());
</script>
<template><view class="page"><view class="hero"><text class="eyebrow">收支分析</text><text class="title">看清资金变化</text><text class="subtle">借款与还款单独统计，不混入日常消费。</text></view><view class="presets"><button @click="preset(7)">近 7 天</button><button @click="preset(30)">近 30 天</button><button @click="startDate=`${month}-01`;load()">本月</button></view><view class="card date-row"><picker mode="date" :value="startDate" @change="startDate=$event.detail.value;load()"><text>{{startDate}}</text></picker><text>至</text><picker mode="date" :value="endDate" @change="endDate=$event.detail.value;load()"><text>{{endDate}}</text></picker></view>
<template v-if="analysis"><view class="metrics"><view class="metric"><text>消费支出</text><text class="strong expense">¥{{money(analysis.consumption_total)}}</text></view><view class="metric"><text>普通收入</text><text class="strong income">¥{{money(analysis.ordinary_income_total)}}</text></view><view class="metric"><text>现金流结余</text><text class="strong">¥{{money(analysis.balance)}}</text></view><view class="metric"><text>日均消费</text><text class="strong">¥{{money(analysis.average_daily_consumption)}}</text></view></view><view class="card insight"><view class="card-title"><text>{{analysis.ai_used?'AI 解读':'智能摘要'}}</text><button class="btn small" :disabled="loading||!analysis.entry_count" @click="load(true)">AI 分析</button></view><text class="headline">{{analysis.insight.headline}}</text><text>{{analysis.insight.summary}}</text><text v-for="x in analysis.insight.suggestions" :key="x" class="tip">· {{x}}</text></view><view class="card"><view class="card-title">消费分类</view><view v-for="x in analysis.categories" :key="x.category" class="category"><view class="between row"><text>{{x.category}}</text><text>¥{{money(x.amount)}} · {{x.percentage}}%</text></view><view class="bar"><view :style="{width:`${x.percentage}%`}"/></view></view><view v-if="!analysis.categories.length" class="empty">该时段没有消费</view></view><view class="card"><view class="card-title">借款与还款</view><view class="flow"><text>借入款</text><text class="income">+ ¥{{money(analysis.borrowed.amount)}}</text></view><view class="flow"><text>收到他人还款</text><text class="income">+ ¥{{money(analysis.repayment_received.amount)}}</text></view><view class="flow"><text>借给别人</text><text class="expense">- ¥{{money(analysis.lent_out.amount)}}</text></view><view class="flow"><text>偿还借款</text><text class="expense">- ¥{{money(analysis.repayment_paid.amount)}}</text></view></view></template>
<view class="card"><view class="card-title"><text>{{month}} 月预算</text></view><view class="row"><input v-model="amount" class="input budget-input" type="digit" placeholder="总预算金额"/><button class="btn primary small" @click="add">添加</button></view><view v-for="b in budgets" :key="b.id" class="flow"><text>{{b.category||'总预算'}} · ¥{{money(b.amount)}}</text><text class="expense" @click="remove(b.id)">删除</text></view></view></view></template>
<style scoped>.presets{display:flex;gap:12rpx;margin-bottom:14rpx}.presets button{flex:1;background:#fffdf8;border-radius:18rpx;font-size:24rpx}.date-row{display:flex;justify-content:space-around}.headline{display:block;font-size:32rpx;font-weight:800;margin-bottom:12rpx}.insight>text{display:block;line-height:1.6}.tip{margin-top:10rpx;color:#785d4f}.category{margin:24rpx 0}.bar{height:12rpx;margin-top:12rpx;background:#eee8de;border-radius:9rpx;overflow:hidden}.bar view{height:100%;background:#e17b52;border-radius:9rpx}.flow{display:flex;justify-content:space-between;padding:20rpx 0;border-bottom:1rpx solid #eee7dd}.budget-input{flex:1;margin-top:0}</style>


