<script setup>
import { computed,reactive,ref } from "vue";import{onShow}from"@dcloudio/uni-app";import{api,showError}from"../../services/api";import{requireLogin}from"../../services/session";
const items=ref([]),show=ref(false),editing=ref(null),selected=ref(null),busy=ref(false);const today=()=>new Date().toLocaleDateString("en-CA");function addMonths(v,n){const d=new Date(`${v}T00:00:00`);d.setMonth(d.getMonth()+n);return d.toLocaleDateString("en-CA")};const blank=()=>({creditor:"",borrowed_at:today(),principal:"",repayment_months:12,annual_rate:"0",repayment_method:"equal_payment",first_payment_date:addMonths(today(),1),note:""});const form=reactive(blank());
function schedule(loan){const p=Number(loan.principal),n=Number(loan.repayment_months),r=Number(loan.annual_rate)/1200;if(!p||!n)return[];let bal=p;const pay=r?p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1):p/n;return Array.from({length:n},(_,i)=>{const interest=bal*r,principal=loan.repayment_method==='equal_principal'?p/n:pay-interest,total=principal+interest;bal=Math.max(0,bal-principal);return{period:i+1,date:addMonths(loan.first_payment_date,i),payment:total,interest,balance:bal}})}
const total=computed(()=>items.value.reduce((s,x)=>s+Number(x.principal),0)),interest=computed(()=>items.value.reduce((s,x)=>s+schedule(x).reduce((a,b)=>a+b.interest,0),0)),preview=computed(()=>schedule(form));const money=v=>Number(v||0).toLocaleString("zh-CN",{minimumFractionDigits:2,maximumFractionDigits:2});
async function load(){if(!requireLogin())return;try{items.value=await api.loans()}catch(e){showError(e)}}function create(){Object.assign(form,blank());editing.value=null;show.value=true}function edit(x){Object.assign(form,{...x,borrowed_at:x.borrowed_at.slice(0,10),first_payment_date:x.first_payment_date.slice(0,10)});editing.value=x.id;show.value=true}async function save(){busy.value=true;try{editing.value?await api.updateLoan(editing.value,{...form}):await api.createLoan({...form});show.value=false;await load()}catch(e){showError(e)}finally{busy.value=false}}function remove(x){uni.showModal({title:"删除借款",content:`删除向“${x.creditor}”的借款？`,success:async r=>{if(r.confirm){await api.deleteLoan(x.id);selected.value=null;await load()}}})}onShow(load);
</script>
<template><view class="page"><view class="hero row between"><view><text class="eyebrow">借款管理</text><text class="title">要还的钱，心里有数</text></view><button class="btn primary small" @click="create">＋ 记借款</button></view><view class="metrics"><view class="metric"><text>本金合计</text><text class="strong">¥{{money(total)}}</text></view><view class="metric"><text>预计利息</text><text class="strong expense">¥{{money(interest)}}</text></view></view><view v-if="!items.length" class="card empty">还没有借款记录</view><view v-for="x in items" :key="x.id" class="card loan" @click="selected=x"><view><text class="name">{{x.creditor}}</text><text class="muted">{{x.borrowed_at.slice(0,10)}} · {{x.repayment_months}} 期 · {{x.annual_rate}}%</text></view><text class="money">¥{{money(x.principal)}}</text></view>
<view v-if="selected" class="sheet-mask" @click.self="selected=null"><view class="sheet"><view class="sheet-head"><text>{{selected.creditor}}</text><text @click="selected=null">×</text></view><view class="metrics"><view class="metric"><text>本金</text><text class="strong">¥{{money(selected.principal)}}</text></view><view class="metric"><text>总利息</text><text class="strong">¥{{money(schedule(selected).reduce((s,x)=>s+x.interest,0))}}</text></view></view><view class="schedule"><view v-for="x in schedule(selected)" :key="x.period" class="flow"><text>第 {{x.period}} 期 · {{x.date}}</text><text>¥{{money(x.payment)}}</text></view></view><view class="row"><button class="btn danger" @click="remove(selected)">删除</button><button class="btn primary grow" @click="edit(selected)">编辑</button></view></view></view>
<view v-if="show" class="sheet-mask" @click.self="show=false"><view class="sheet"><view class="sheet-head"><text>{{editing?'编辑借款':'新增借款'}}</text><text @click="show=false">×</text></view><label class="field">借款来源<input v-model="form.creditor" class="input" placeholder="银行或个人"/></label><label class="field">本金<input v-model="form.principal" class="input" type="digit"/></label><label class="field">借款日期<picker mode="date" :value="form.borrowed_at" @change="form.borrowed_at=$event.detail.value"><view class="picker">{{form.borrowed_at}}</view></picker></label><label class="field">还款期数<input v-model.number="form.repayment_months" class="input" type="number"/></label><label class="field">年利率 %<input v-model="form.annual_rate" class="input" type="digit"/></label><label class="field">还款方式<picker :range="['等额本息','等额本金']" @change="form.repayment_method=$event.detail.value?'equal_principal':'equal_payment'"><view class="picker">{{form.repayment_method==='equal_payment'?'等额本息':'等额本金'}}</view></picker></label><label class="field">首次还款日<picker mode="date" :value="form.first_payment_date" @change="form.first_payment_date=$event.detail.value"><view class="picker">{{form.first_payment_date}}</view></picker></label><label class="field">备注<textarea v-model="form.note" class="textarea"/></label><view v-if="preview.length" class="preview">首期约 ¥{{money(preview[0].payment)}} · 总利息 ¥{{money(preview.reduce((s,x)=>s+x.interest,0))}}</view><button class="btn primary" :disabled="busy" @click="save">保存借款</button></view></view></view></template>
<style scoped>.hero>view{flex:1}.loan{display:flex;align-items:center;justify-content:space-between}.name{display:block;font-size:31rpx;font-weight:800;margin-bottom:8rpx}.schedule{max-height:48vh;overflow:auto;margin-bottom:20rpx}.flow{display:flex;justify-content:space-between;padding:18rpx 0;border-bottom:1rpx solid #eee6db;font-size:24rpx}.grow{flex:1}.preview{margin-bottom:20rpx;padding:18rpx;background:#fff3e8;border-radius:16rpx;color:#a6593e}</style>


